title: Happy Birthday
To_name: 小猪猪
from_name: 小狗狗
crypto: 1129

# 文字动画配置
font_animation:
  fontSize: 300  # 字体大小
  fontFamily: 'Avenir, Helvetica Neue, Helvetica, Arial, sans-serif' # 字体样式

# 各屏幕文本内容
screens:
  # 第一屏
  screen1:
    messages1:
      - "愿你能精致到老，眼里满是星光。"
      - "开朗面对生活，笑里全是坦荡。"
      - "阳光下永远像个孩子，"
      - "风雨里像个大人，无畏亦无惧。"
      - "你若不伤，岁月无恙。"
    messages2:
      - "有幸与你相识，"
      - "与你相识的这段时间以来"
      - "真的超级超级开心！"
      - "承蒙时光不弃，感谢相遇。"
      - "(往下滑，有惊喜!)"
  
  # 第二屏
  screen2:
    message1:
      - "祝你所有的希望都能如愿，"
      - "所有的梦想都能实现，"
      - "所有的期待都能出现，"
      - "所有的付出都能兑现在你生日来临之即。"
  
  # 第三屏
  screen3:
    message1:
      - "百事可乐"
      - "万事芬达"
      - "天天哇哈哈"
      - "月月乐百事"
    message2:
      - "年年高乐高"
      - "心情似雪碧"
      - "永远心飞扬"
  
  # 第四屏
  screen4:
    message1:
      - "愿你"
      - "狂吃不胖，深情不负，傻人傻福，"
      - "一直幸运。一生努力，一生被爱，"
      - "想要的都拥有，得不到的都释怀。🌈"
    message2:
      - "悄悄许个愿望吧！"
      - "今年一定能实现！！！"
  
  # 第五屏
  screen5:
    message:
      - "Hi! 小猪猪，"
      - "今天是你的18岁生日!"
      - "在这个时刻，"
      - "首先送上我的祝福，希望你身体健康，所有的烦恼统统全忘掉。"
      - "希望每天都能开开心心，吃特别多的好吃的，咋吃都不胖，"
      - "去特别多好玩的地方，咋玩都不会累。"
      - "努力去成为自己想要成为的样子，好吗？好的！"