title: Happy Birthday
To_name: å°çŒªçŒª
from_name: å°ç‹—ç‹—
crypto: 1129

# æ–‡å­—åŠ¨ç”»é…ç½®
font_animation:
  fontSize: 300  # å­—ä½“å¤§å°
  fontFamily: 'Avenir, Helvetica Neue, Helvetica, Arial, sans-serif' # å­—ä½“æ ·å¼

# ç•Œé¢éŸ³ä¹é…ç½®
music:
  BirthdayCake: "/templates/music/1.mp3"
  Memories: "/templates/music/2.mp3"

# å„å±å¹•æ–‡æœ¬å†…å®¹
screens:
  birthday_logo: "/templates/img/HappyBirthday.png"
  # ç¬¬ä¸€å±
  screen1:
    messages1:
      - "æ„¿ä½ èƒ½ç²¾è‡´åˆ°è€ï¼Œçœ¼é‡Œæ»¡æ˜¯æ˜Ÿå…‰ã€‚"
      - "å¼€æœ—é¢å¯¹ç”Ÿæ´»ï¼Œç¬‘é‡Œå…¨æ˜¯å¦è¡ã€‚"
      - "é˜³å…‰ä¸‹æ°¸è¿œåƒä¸ªå­©å­ï¼Œ"
      - "é£é›¨é‡Œåƒä¸ªå¤§äººï¼Œæ— ç•äº¦æ— æƒ§ã€‚"
      - "ä½ è‹¥ä¸ä¼¤ï¼Œå²æœˆæ— æ™ã€‚"

    messages2:
      - "æœ‰å¹¸ä¸ä½ ç›¸è¯†ï¼Œ"
      - "ä¸ä½ ç›¸è¯†çš„è¿™æ®µæ—¶é—´ä»¥æ¥ï¼Œ"
      - "çœŸçš„è¶…çº§è¶…çº§å¼€å¿ƒï¼"
      - "æ‰¿è’™æ—¶å…‰ä¸å¼ƒï¼Œæ„Ÿè°¢ç›¸é‡ã€‚"
      - "(å¾€ä¸‹æ»‘ï¼Œæœ‰æƒŠå–œ!)"
  
  # ç¬¬äºŒå±
  screen2:
    image1: "/templates/img/zt.jpg"

    image2: "/templates/img/timg.gif"
    message1:
      - "ç¥ä½ æ‰€æœ‰çš„å¸Œæœ›éƒ½èƒ½å¦‚æ„¿ï¼Œ"
      - "æ‰€æœ‰çš„æ¢¦æƒ³éƒ½èƒ½å®ç°ï¼Œ"
      - "æ‰€æœ‰çš„æœŸå¾…éƒ½èƒ½å‡ºç°ï¼Œ"
      - "æ‰€æœ‰çš„ä»˜å‡ºéƒ½èƒ½å…‘ç°åœ¨ä½ ç”Ÿæ—¥æ¥ä¸´ä¹‹å³ã€‚"
  
  # ç¬¬ä¸‰å±
  screen3:
    image1: "/templates/img/di2.png"

    image2: "/templates/img/di21.jpg"
    message1:
      - "ç™¾äº‹å¯ä¹"
      - "ä¸‡äº‹èŠ¬è¾¾"
      - "å¤©å¤©å“‡å“ˆå“ˆ"
      - "æœˆæœˆä¹ç™¾äº‹"
    
    image3: "/templates/img/di54.png"
    message2:
      - "å¹´å¹´é«˜ä¹é«˜"
      - "å¿ƒæƒ…ä¼¼é›ªç¢§"
      - "æ°¸è¿œå¿ƒé£æ‰¬"
  
  # ç¬¬å››å±
  screen4:
    image1: "/templates/img/di22.jpg"
    message1:
      - "æ„¿ä½ "
      - "ç‹‚åƒä¸èƒ–ï¼Œæ·±æƒ…ä¸è´Ÿï¼Œå‚»äººå‚»ç¦ï¼Œ"
      - "ä¸€ç›´å¹¸è¿ã€‚ä¸€ç”ŸåŠªåŠ›ï¼Œä¸€ç”Ÿè¢«çˆ±ï¼Œ"
      - "æƒ³è¦çš„éƒ½æ‹¥æœ‰ï¼Œå¾—ä¸åˆ°çš„éƒ½é‡Šæ€€ã€‚ğŸŒˆ"

    image2: "/templates/img/di24.jpg"
    message2:
      - "æ‚„æ‚„è®¸ä¸ªæ„¿æœ›å§ï¼"
      - "ä»Šå¹´ä¸€å®šèƒ½å®ç°ï¼ï¼ï¼"
  
  # ç¬¬äº”å±
  screen5:
    image1: "/templates/img/haha.jpg"
    message:
      - "Hi! å°çŒªçŒªï¼Œ"
      - "ä»Šå¤©æ˜¯ä½ çš„18å²ç”Ÿæ—¥!"
      - "åœ¨è¿™ä¸ªæ—¶åˆ»ï¼Œ"
      - "é¦–å…ˆé€ä¸Šæˆ‘çš„ç¥ç¦ï¼Œå¸Œæœ›ä½ èº«ä½“å¥åº·ï¼Œæ‰€æœ‰çš„çƒ¦æ¼ç»Ÿç»Ÿå…¨å¿˜æ‰ã€‚"
      - "å¸Œæœ›æ¯å¤©éƒ½èƒ½å¼€å¼€å¿ƒå¿ƒï¼Œåƒç‰¹åˆ«å¤šçš„å¥½åƒçš„ï¼Œå’‹åƒéƒ½ä¸èƒ–ï¼Œ"
      - "å»ç‰¹åˆ«å¤šå¥½ç©çš„åœ°æ–¹ï¼Œå’‹ç©éƒ½ä¸ä¼šç´¯ã€‚"
      - "åŠªåŠ›å»æˆä¸ºè‡ªå·±æƒ³è¦æˆä¸ºçš„æ ·å­ï¼Œå¥½å—ï¼Ÿå¥½çš„ï¼"